dependencies {
    // spring boot
    implementation "org.springframework.boot:spring-boot-starter-aop"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-web"

    implementation "org.apache.commons:commons-lang3:${project.ext.commonsLang3Version}"
    implementation "commons-io:commons-io:${project.ext.commonsIOVersion}"
    implementation "net.coobird:thumbnailator:${project.ext.thumbnailatorVersion}"
}
