dependencies {
    // spring boot
    implementation "org.springframework.boot:spring-boot-starter-aop"
    implementation "org.springframework.boot:spring-boot-starter-data-mongodb"
    api "org.springframework.security:spring-security-core"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-web"

    implementation "org.mongodb:mongodb-driver-sync:${project.ext.mongoDriverVersion}"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${project.ext.springDocVersion}"

    // shared
    api project(':shared:common')
}
